//! Raw FFI bindings to LibreDWG
//!
//! These bindings are automatically generated by bindgen.
//! Do not edit this file directly.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
