//! Manufacturing output generation
//!
//! Generates Gerber, drill files, BOM, and other manufacturing outputs.

use std::io::Write;

use crate::error::{EdaError, Result};
use crate::pcb::{Board, LayerType, Track, Via, Zone};
use crate::schematic::Schematic;

/// Gerber format options
#[derive(Debug, Clone)]
pub struct GerberOptions {
    /// Use X2 format (extended attributes)
    pub x2_format: bool,
    
    /// Include aperture attributes
    pub include_attributes: bool,
    
    /// Coordinate precision (integer places, decimal places)
    pub precision: (u8, u8),
    
    /// Use inches (false = mm)
    pub use_inches: bool,
}

impl Default for GerberOptions {
    fn default() -> Self {
        Self {
            x2_format: true,
            include_attributes: true,
            precision: (4, 6),
            use_inches: false,
        }
    }
}

/// Gerber file generator
pub struct GerberGenerator {
    options: GerberOptions,
}

impl GerberGenerator {
    pub fn new(options: GerberOptions) -> Self {
        Self { options }
    }

    /// Generate Gerber file for a layer
    pub fn generate_layer<W: Write>(&self, board: &Board, layer_name: &str, writer: &mut W) -> Result<()> {
        let layer = board
            .find_layer(layer_name)
            .ok_or_else(|| EdaError::InvalidLayer(layer_name.to_string()))?;

        // Write Gerber header
        self.write_header(writer, layer_name)?;

        // Write aperture definitions
        self.write_aperture_definitions(writer, board)?;

        // Write layer contents based on type
        match layer.layer_type {
            LayerType::Signal | LayerType::Plane => {
                // Write tracks on this layer
                for track in &board.tracks {
                    if track.layer == layer.id {
                        self.write_track(writer, track)?;
                    }
                }

                // Write vias (through-hole pads)
                for via in &board.vias {
                    self.write_via(writer, via)?;
                }

                // Write zones
                for zone in &board.zones {
                    if zone.layer == layer.id {
                        self.write_zone(writer, zone)?;
                    }
                }
            }
            LayerType::Silkscreen => {
                // Write silkscreen graphics
                self.write_silkscreen(writer, board)?;
            }
            LayerType::Mask => {
                // Write solder mask openings
                self.write_mask(writer, board)?;
            }
            LayerType::Fabrication => {
                // Write board outline
                self.write_outline(writer, board)?;
            }
            _ => {}
        }

        // Write Gerber footer
        self.write_footer(writer)?;

        Ok(())
    }

    fn write_header<W: Write>(&self, writer: &mut W, layer_name: &str) -> Result<()> {
        // Gerber header
        writeln!(writer, "G04 Generated by ZCAD EDA*")?;
        writeln!(writer, "G04 Layer: {}*", layer_name)?;
        
        if self.options.x2_format {
            writeln!(writer, "%TF.GenerationSoftware,ZCAD,EDA,1.0*%")?;
            writeln!(writer, "%TF.FileFunction,{}*%", layer_name)?;
        }

        // Format specification
        let (int_places, dec_places) = self.options.precision;
        writeln!(
            writer,
            "%FSLAX{}{}Y{}{}*%",
            int_places, dec_places, int_places, dec_places
        )?;

        // Units
        if self.options.use_inches {
            writeln!(writer, "%MOIN*%")?;
        } else {
            writeln!(writer, "%MOMM*%")?;
        }

        Ok(())
    }

    fn write_aperture_definitions<W: Write>(&self, writer: &mut W, _board: &Board) -> Result<()> {
        // Define standard apertures
        // D10: Circle for vias
        writeln!(writer, "%ADD10C,0.800000*%")?;
        // D11: Rectangle for SMD pads
        writeln!(writer, "%ADD11R,1.000000X1.200000*%")?;
        // D12-D20: Track widths
        writeln!(writer, "%ADD12C,0.150000*%")?;
        writeln!(writer, "%ADD13C,0.200000*%")?;
        writeln!(writer, "%ADD14C,0.250000*%")?;
        writeln!(writer, "%ADD15C,0.300000*%")?;
        writeln!(writer, "%ADD16C,0.400000*%")?;
        writeln!(writer, "%ADD17C,0.500000*%")?;

        Ok(())
    }

    fn write_track<W: Write>(&self, writer: &mut W, track: &Track) -> Result<()> {
        // Select aperture based on track width
        let aperture = self.width_to_aperture(track.width);
        writeln!(writer, "D{}*", aperture)?;

        // Move to start and draw to end
        let (sx, sy) = self.format_coord(track.start.x, track.start.y);
        let (ex, ey) = self.format_coord(track.end.x, track.end.y);
        writeln!(writer, "X{}Y{}D02*", sx, sy)?;
        writeln!(writer, "X{}Y{}D01*", ex, ey)?;

        Ok(())
    }

    fn write_via<W: Write>(&self, writer: &mut W, via: &Via) -> Result<()> {
        // Select via aperture
        writeln!(writer, "D10*")?;

        // Flash at via position
        let (x, y) = self.format_coord(via.position.x, via.position.y);
        writeln!(writer, "X{}Y{}D03*", x, y)?;

        Ok(())
    }

    fn write_zone<W: Write>(&self, writer: &mut W, zone: &Zone) -> Result<()> {
        if zone.outline.is_empty() {
            return Ok(());
        }

        // Start region
        writeln!(writer, "G36*")?;

        // Move to first point
        let first = &zone.outline[0];
        let (x, y) = self.format_coord(first.x, first.y);
        writeln!(writer, "X{}Y{}D02*", x, y)?;

        // Draw outline
        for point in zone.outline.iter().skip(1) {
            let (x, y) = self.format_coord(point.x, point.y);
            writeln!(writer, "X{}Y{}D01*", x, y)?;
        }

        // Close region
        let (x, y) = self.format_coord(first.x, first.y);
        writeln!(writer, "X{}Y{}D01*", x, y)?;
        writeln!(writer, "G37*")?;

        Ok(())
    }

    fn write_silkscreen<W: Write>(&self, _writer: &mut W, _board: &Board) -> Result<()> {
        // TODO: Write silkscreen graphics
        Ok(())
    }

    fn write_mask<W: Write>(&self, _writer: &mut W, _board: &Board) -> Result<()> {
        // TODO: Write solder mask openings
        Ok(())
    }

    fn write_outline<W: Write>(&self, writer: &mut W, board: &Board) -> Result<()> {
        use crate::pcb::BoardOutline;
        
        // Select outline aperture (thin line)
        writeln!(writer, "D12*")?;

        match &board.outline {
            BoardOutline::Rectangle { width, height } => {
                let (x0, y0) = self.format_coord(0.0, 0.0);
                let (x1, y1) = self.format_coord(*width, 0.0);
                let (x2, y2) = self.format_coord(*width, *height);
                let (x3, y3) = self.format_coord(0.0, *height);

                writeln!(writer, "X{}Y{}D02*", x0, y0)?;
                writeln!(writer, "X{}Y{}D01*", x1, y1)?;
                writeln!(writer, "X{}Y{}D01*", x2, y2)?;
                writeln!(writer, "X{}Y{}D01*", x3, y3)?;
                writeln!(writer, "X{}Y{}D01*", x0, y0)?;
            }
            BoardOutline::Polygon(points) => {
                if let Some(first) = points.first() {
                    let (x, y) = self.format_coord(first.x, first.y);
                    writeln!(writer, "X{}Y{}D02*", x, y)?;

                    for point in points.iter().skip(1) {
                        let (x, y) = self.format_coord(point.x, point.y);
                        writeln!(writer, "X{}Y{}D01*", x, y)?;
                    }

                    let (x, y) = self.format_coord(first.x, first.y);
                    writeln!(writer, "X{}Y{}D01*", x, y)?;
                }
            }
        }

        Ok(())
    }

    fn write_footer<W: Write>(&self, writer: &mut W) -> Result<()> {
        writeln!(writer, "M02*")?;
        Ok(())
    }

    fn width_to_aperture(&self, width: f64) -> u32 {
        // Map track width to aperture number
        if width <= 0.15 {
            12
        } else if width <= 0.20 {
            13
        } else if width <= 0.25 {
            14
        } else if width <= 0.30 {
            15
        } else if width <= 0.40 {
            16
        } else {
            17
        }
    }

    fn format_coord(&self, x: f64, y: f64) -> (i64, i64) {
        let (_, dec_places) = self.options.precision;
        let scale = 10_i64.pow(dec_places as u32);
        
        let x_scaled = (x * scale as f64).round() as i64;
        let y_scaled = (y * scale as f64).round() as i64;
        
        (x_scaled, y_scaled)
    }
}

impl Default for GerberGenerator {
    fn default() -> Self {
        Self::new(GerberOptions::default())
    }
}

/// Drill file format
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DrillFormat {
    Excellon,
    Excellon2,
}

/// Drill file generator
pub struct DrillGenerator {
    format: DrillFormat,
    use_inches: bool,
}

impl DrillGenerator {
    pub fn new(format: DrillFormat) -> Self {
        Self {
            format,
            use_inches: false,
        }
    }

    pub fn generate<W: Write>(&self, board: &Board, writer: &mut W) -> Result<()> {
        // Header
        writeln!(writer, "M48")?;
        writeln!(writer, "; Generated by ZCAD EDA")?;
        
        if self.use_inches {
            writeln!(writer, "INCH")?;
        } else {
            writeln!(writer, "METRIC")?;
        }

        // Collect unique drill sizes
        let mut drill_sizes: Vec<f64> = Vec::new();
        for via in &board.vias {
            if !drill_sizes.iter().any(|&d| (d - via.drill).abs() < 0.001) {
                drill_sizes.push(via.drill);
            }
        }
        drill_sizes.sort_by(|a, b| a.partial_cmp(b).unwrap());

        // Define tools
        for (i, size) in drill_sizes.iter().enumerate() {
            writeln!(writer, "T{}C{:.3}", i + 1, size)?;
        }
        writeln!(writer, "%")?;

        // Drill hits for each tool
        for (i, size) in drill_sizes.iter().enumerate() {
            writeln!(writer, "T{}", i + 1)?;
            
            for via in &board.vias {
                if (via.drill - size).abs() < 0.001 {
                    writeln!(writer, "X{:.3}Y{:.3}", via.position.x, via.position.y)?;
                }
            }
        }

        // Footer
        writeln!(writer, "M30")?;

        Ok(())
    }
}

impl Default for DrillGenerator {
    fn default() -> Self {
        Self::new(DrillFormat::Excellon2)
    }
}

/// BOM (Bill of Materials) entry
#[derive(Debug, Clone)]
pub struct BomEntry {
    /// Reference designators
    pub references: Vec<String>,
    /// Quantity
    pub quantity: usize,
    /// Value
    pub value: String,
    /// Description
    pub description: String,
    /// Footprint
    pub footprint: String,
    /// Manufacturer
    pub manufacturer: Option<String>,
    /// Part number
    pub mpn: Option<String>,
}

/// BOM generator
pub struct BomGenerator;

impl BomGenerator {
    pub fn generate(_schematic: &Schematic) -> Vec<BomEntry> {
        // TODO: Implement BOM generation from schematic
        Vec::new()
    }

    pub fn to_csv(entries: &[BomEntry]) -> String {
        let mut csv = String::new();
        csv.push_str("Reference,Quantity,Value,Description,Footprint,Manufacturer,MPN\n");

        for entry in entries {
            csv.push_str(&format!(
                "\"{}\",{},\"{}\",\"{}\",\"{}\",\"{}\",\"{}\"\n",
                entry.references.join(","),
                entry.quantity,
                entry.value,
                entry.description,
                entry.footprint,
                entry.manufacturer.as_deref().unwrap_or(""),
                entry.mpn.as_deref().unwrap_or(""),
            ));
        }

        csv
    }
}

/// Pick and place file generator
pub struct PickPlaceGenerator;

impl PickPlaceGenerator {
    pub fn generate(board: &Board) -> String {
        let mut output = String::new();
        output.push_str("Reference,Value,Footprint,PosX,PosY,Rotation,Side\n");

        for fp in &board.footprints {
            output.push_str(&format!(
                "{},{},{},{:.3},{:.3},{:.1},{}\n",
                fp.reference,
                fp.value.as_deref().unwrap_or(""),
                "", // TODO: Get footprint name
                fp.position.x,
                fp.position.y,
                fp.rotation,
                if fp.on_back { "Bottom" } else { "Top" },
            ));
        }

        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gerber_generation() {
        let board = Board::new("Test", 100.0, 80.0);
        let generator = GerberGenerator::default();
        let mut output = Vec::new();
        
        let result = generator.generate_layer(&board, "F.Cu", &mut output);
        assert!(result.is_ok());
        
        let content = String::from_utf8(output).unwrap();
        assert!(content.contains("G04"));
        assert!(content.contains("M02"));
    }

    #[test]
    fn test_drill_generation() {
        let board = Board::new("Test", 100.0, 80.0);
        let generator = DrillGenerator::default();
        let mut output = Vec::new();
        
        let result = generator.generate(&board, &mut output);
        assert!(result.is_ok());
        
        let content = String::from_utf8(output).unwrap();
        assert!(content.contains("M48"));
        assert!(content.contains("M30"));
    }
}
